# ======================================
# CONFIGURACIÓN - VERSIÓN MUY FLEXIBLE (PARA GENERAR SEÑALES)
# ======================================

SIMULATION_MODE = True
EXCHANGE_NAME = "okx"

CAPITAL_INICIAL = 1000
MAX_POSICIONES = 4
USO_CAPITAL = 0.60

# FILTROS MUY PERMISIVOS
RSI_MIN_BASE = 20
RSI_MAX_BASE = 80
VOLATILIDAD_MAX_BASE = 0.20
VOLATILIDAD_MIN_BASE = 0.001
SCORE_MINIMO_BASE = 1          # Cualquier score positivo

ATR_PERIOD = 14
ATR_MULTIPLIER = 1.5
TRAILING_GAP_DINAMICO = True

# TAMAÑOS (puedes mantenerlos)
TAMANO_ELITE = 0.12
TAMANO_OPORTUNISTA_BUENA = 0.08

COOLDOWN_BASE = 10
COOLDOWN_MAX = 60
COOLDOWN_MIN = 5

TIMEFRAME = "5m"
CYCLE_TIME = 10

# UNIVERSO (puedes reducirlo a unos pocos para pruebas rápidas)
CRYPTOS = [
    "BTC/USDT", "ETH/USDT", "SOL/USDT", "ADA/USDT", "DOGE/USDT"
]

# CORRELACIÓN (simplificada)
CORRELACION = {
    "L1": ["BTC/USDT", "ETH/USDT"],
    "L2": ["SOL/USDT"],
    "L3": ["ADA/USDT"],
    "MEME": ["DOGE/USDT"]
}

# IA (sin cambios)
RETRAIN_EVERY_TRADES = 50
OPTIMIZE_EVERY_HOURS = 4
LOOKBACK_DAYS = 30

# API KEYS (igual)
OKX_API_KEY = "TU_API_KEY"
...