# ======================================
# CONFIGURACIÓN - VERSIÓN PROFESIONAL (ELITE + BUENA)
# ======================================

SIMULATION_MODE = True
EXCHANGE_NAME = "okx"

CAPITAL_INICIAL = 1000
MAX_POSICIONES = 3
USO_CAPITAL = 0.60

# FILTROS TÉCNICOS (intermedios, no demasiado estrictos)
RSI_MIN_BASE = 40
RSI_MAX_BASE = 72
VOLATILIDAD_MAX_BASE = 0.12
VOLATILIDAD_MIN_BASE = 0.0025
SCORE_MINIMO_BASE = 2          # Mínimo para considerar, pero Elite requiere 3

ATR_PERIOD = 14
ATR_MULTIPLIER = 1.5
TRAILING_GAP_DINAMICO = True

# TAMAÑOS DE POSICIÓN (solo dos categorías)
TAMANO_ELITE = 0.12            # 12%
TAMANO_OPORTUNISTA_BUENA = 0.08 # 8%

# COOLDOWN RÁPIDO (para tener oportunidades)
COOLDOWN_BASE = 10
COOLDOWN_MAX = 60
COOLDOWN_MIN = 5

TIMEFRAME = "5m"
CYCLE_TIME = 10

# UNIVERSO DE ACTIVOS (20 activos líquidos)
CRYPTOS = [
    "BTC/USDT", "ETH/USDT", "SOL/USDT", "AVAX/USDT", "ADA/USDT",
    "LINK/USDT", "ATOM/USDT", "INJ/USDT", "NEAR/USDT", "APT/USDT",
    "OP/USDT", "RENDER/USDT", "AR/USDT", "POL/USDT", "XRP/USDT",
    "DOGE/USDT", "WIF/USDT", "PEPE/USDT", "SUI/USDT", "SEI/USDT"
]

# CORRELACIÓN (evitar agrupaciones)
CORRELACION = {
    "L1": ["BTC/USDT", "ETH/USDT"],
    "L2": ["SOL/USDT", "AVAX/USDT"],
    "L3": ["ADA/USDT", "XRP/USDT", "POL/USDT"],
    "L4": ["LINK/USDT", "ATOM/USDT"],
    "L5": ["INJ/USDT", "NEAR/USDT", "APT/USDT"],
    "L6": ["OP/USDT", "AR/USDT", "RENDER/USDT"],
    "MEME": ["DOGE/USDT", "WIF/USDT", "PEPE/USDT"],
    "L1_ALT": ["SUI/USDT", "SEI/USDT"]
}

# IA Y APRENDIZAJE
RETRAIN_EVERY_TRADES = 50
OPTIMIZE_EVERY_HOURS = 4
LOOKBACK_DAYS = 30

# API KEYS (rellenar después)
OKX_API_KEY = "TU_API_KEY"
OKX_SECRET_KEY = "TU_SECRET"
OKX_PASSPHRASE = "TU_PASSPHRASE"
BINANCE_API_KEY = "TU_API_KEY"
BINANCE_SECRET_KEY = "TU_SECRET"