# ======================================
# CONFIGURACIÓN - VERSIÓN MUY PERMISIVA (PARA GENERAR ACTIVIDAD)
# ======================================

SIMULATION_MODE = True
EXCHANGE_NAME = "okx"

CAPITAL_INICIAL = 1000
MAX_POSICIONES = 4
USO_CAPITAL = 0.60

# FILTROS MUY AMPLIOS (para que haya señales)
RSI_MIN_BASE = 20
RSI_MAX_BASE = 80
VOLATILIDAD_MAX_BASE = 0.25
VOLATILIDAD_MIN_BASE = 0.0005
SCORE_MINIMO_BASE = 1          # Cualquier score positivo

ATR_PERIOD = 14
ATR_MULTIPLIER = 1.0           # Stop más sensible (1.0 en lugar de 1.5)
TRAILING_GAP_DINAMICO = True

# TAMAÑOS (se mantienen)
TAMANO_ELITE = 0.12
TAMANO_OPORTUNISTA_BUENA = 0.08

# COOLDOWN más rápido para más operaciones
COOLDOWN_BASE = 5
COOLDOWN_MAX = 30
COOLDOWN_MIN = 3

TIMEFRAME = "5m"
CYCLE_TIME = 10

# UNIVERSO REDUCIDO (incluye varios grupos para diversificar)
CRYPTOS = [
    "BTC/USDT", "ETH/USDT", "SOL/USDT", "ADA/USDT", "DOGE/USDT",
    "LINK/USDT", "DOT/USDT", "AAVE/USDT"
]

# CORRELACIÓN (grupos claros)
CORRELACION = {
    "L1": ["BTC/USDT", "ETH/USDT"],
    "L2": ["SOL/USDT"],
    "L3": ["ADA/USDT"],
    "MEME": ["DOGE/USDT"],
    "L4": ["LINK/USDT"],
    "L5": ["DOT/USDT"],
    "L6": ["AAVE/USDT"]
}

# IA
RETRAIN_EVERY_TRADES = 50
OPTIMIZE_EVERY_HOURS = 4
LOOKBACK_DAYS = 30

# API KEYS (cambia por las tuyas)
OKX_API_KEY = "TU_API_KEY"
OKX_SECRET_KEY = "TU_SECRET"
OKX_PASSPHRASE = "TU_PASSPHRASE"
BINANCE_API_KEY = "TU_API_KEY"
BINANCE_SECRET_KEY = "TU_SECRET"